<!DOCTYPE html>
<html>
<title>promise的几个关键问题</title>
<body>
    <script>
        /* 
        6.promise异常传透？
            (1)当使用promise的then链式调用时,可以在最后指定失败的回调
            (2)前面任何操作出了异常，都会传到最后失败的回调中处理
            
        7.中断promise链？
            (1)当使用promise的then链式调用时，在中间中断，不再调用后面的回调函数
            (2)办法：在回调函数中返回一个pendding状态的promise对象
        */

        /* 
        4.promise.then()返回的新promise的结果由什么决定？
            (1)简单表达:由then()指定的回调函数执行的结果决定
            (2)详细表达:
                1.如果抛出异常，新的promise变为rejected，reason为抛出的异常
                2.如果返回的是非promise的任意值，新promise变为resolved,value为返回的值
                3.如果返回的是另一个新promise,此promise的结果就会成为新的promise的结果
        */
        new Promise((resolve,reject) => {
            // resolve(1)
            reject(1)
        }).then(
            value => {
                console.log('onResolved1()',value);
                return 2
            },
            reason => {throw reason}
        ).then(
            value => {
                console.log('onResolved2()',value);
                return 3
            },
            reason => {throw reason}
        ).then(
            value => {
                console.log('onResolved3()',value);
            },
        ).catch(
            reason => {
                console.log('onRejected1()',reason);
                // throw reason
                return new Promise.reject(reason)
            }
        ).then(
            value => {
                console.log('onResolved4()',value);
            },
            reason => {
                console.log('onRejected4()',reason);
            }
        )
    </script>
</body>
</html>